{{- $fullName := .Release.Name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-mongo1
  labels:
    app: mongo1
    role: master
    tier: backend
spec:
  ports:
    - port: 27017
      targetPort: 27017
  # Replace with the IP of your minikube node / master node if you want external access
  externalIPs:
    - 192.168.1.104 
  selector:
    app: mongo1
    role: master
    tier: backend
