{{- $fullName := .Release.Name -}}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ $fullName }}-mongo-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 0.001Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/mongo"
