{{- $fullName := .Release.Name -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: {{ $fullName }}-nginx-ingress-controller
  namespace: ingress-nginx
spec: 
  replicas: 1
  revisionHistoryLimit: 3
  template: 
    metadata: 
      labels: 
        app: {{ template "blue-green.name" . }}
        chart: {{ template "blue-green.chart" . }}
        release: {{ .Release.Name }}
        k8s-app: {{ $fullName }}-nginx-ingress-lb
    spec: 
      containers: 
        - args: 
            - /nginx-ingress-controller
            - "--default-backend-service=$(POD_NAMESPACE)/{{ $fullName }}-default-http-backend"
          env: 
            - name: POD_NAME
              valueFrom: 
                fieldRef: 
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom: 
                fieldRef: 
                  fieldPath: metadata.namespace
          image: "gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.5"
          imagePullPolicy: IfNotPresent
          livenessProbe: 
            httpGet: 
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
          name: nginx-ingress-controller
          ports: 
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
      terminationGracePeriodSeconds: 60
