---

apiVersion: v1
kind: Service
metadata:
  name: atlas-lb
  namespace: atlas
  labels:
    app: atlas
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.122
  ports:
  - 
    name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: atlas
    release: atlas-r1
