apiVersion: v1
appVersion: 0.50.2
description: A Helm chart for Datawire Ambassador
engine: gotpl
home: https://www.getambassador.io/
icon: https://www.getambassador.io/images/logo.png
keywords:
- api gateway
- ambassador
- datawire
- envoy
maintainers:
- email: markus@maga.se
  name: flydiverny
- email: flynn@datawire.io
  name: Flynn
name: ambassador
sources:
- https://github.com/datawire/ambassador
- https://github.com/prometheus/statsd_exporter
version: 1.1.4
