---

apiVersion: v1
kind: Service
metadata:
  name: kube-apps
  namespace: kube-apps
  labels:
    app: kube-apps
spec:
  type: ClusterIP
  ports:
  -
    name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: kube-apps-r1
    release: kube-apps-r1
