---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-terminal
  labels:
    app: nfs-terminal
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 40Gi
  storageClassName: nfs-terminal
  nfs:
    server: repo0
    path: /var/nfs/terminal
