---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-terminal
  labels:
    app: nfs-terminal
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
