apiVersion: v1
kind: Service
metadata:
  name: {{ template "chartmuseum-ui.fullname" . }}
  labels:
    app: {{ template "chartmuseum-ui.name" . }}
    chart: {{ template "chartmuseum-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - 
    name: http
    port: 3000
    protocol: TCP
    targetPort: http
  selector:
    app: {{ template "chartmuseum-ui.name" . }}
    release: {{ .Release.Name }}
