---

apiVersion: v1
kind: Service
metadata:
  name: terminal
  namespace: terminal
  labels:
    app: terminal
spec:
  type: ClusterIP
  ports:
  - 
    name: https
    port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: terminal
    release: "terminal-r1"
