---

apiVersion: v1
kind: Service
metadata:
  name: terminal-lb
  namespace: terminal
  labels:
    app: terminal
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.121
  ports:
  - 
    name: https
    port: 443
    protocol: TCP
    targetPort: 5000
  selector:
    app: terminal
    release: "terminal-r1"
